[device_ports]

PMOS = ["Drain", "Source", "Gate", "Body"]
NMOS = ["Drain", "Source", "Gate", "Body"]
Voltage = ["Positive", "Negative"]
Current = ["In", "Out"]
NPN = ["Base", "Emitter", "Collector"]
PNP = ["Base", "Emitter", "Collector"]
Diode = ["In", "Out"]
Diso_amp = ["InN", "InP", "Out"]
Siso_amp = ["In", "Out"]
Dido_amp = ["InN", "InP", "OutN", "OutP"]
Cap = ["Pos", "Neg"]
Gnd = ["Port"]
Vdd = ["Port"]
Ind = ["Pos", "Neg"]
Res = ["Pos", "Neg"]

[port_merge]

PMOS = ["DS", "DS", "G", "B"]
NMOS = ["DS", "DS", "G", "B"]
Voltage = ["P", "P"]
Current = ["P", "P"]
NPN = ["B", "E", "C"]
PNP = ["B", "E", "C"]
Diode = ["I", "O"]
Diso_amp = ["IN", "IP", "O"]
Siso_amp = ["I", "O"]
Dido_amp = ["IN", "IP", "ON", "OP"]
Cap = ["P", "P"]
Gnd = ["P"]
Vdd = ["P"]
Ind = ["P", "P"]
Res = ["P", "P"]